import { ArrowRight, CheckCircle2, ChevronDown } from 'lucide-react';
import { useState } from 'react';
import { Link } from 'react-router-dom';

export function PricingPage() {
  const [openFaq, setOpenFaq] = useState<number | null>(0);

  const faqs = [
    {
      question: "How are the financial estimates calculated?",
      answer: "We use your building's reported energy usage from the Chicago Benchmarking Ordinance and apply current ComEd and Peoples Gas commercial rates. We then compare your performance to similar buildings in Chicago to identify the gap between your current spend and optimal efficiency."
    },
    {
      question: "What data does Civic Energy use?",
      answer: "We aggregate data from the City of Chicago Benchmarking Ordinance, ComEd and Peoples Gas rate schedules, NOAA Chicago weather station, Cook County Assessor property records, and ENERGY STAR Portfolio Manager."
    },
    {
      question: "Is my building's data private?",
      answer: "The initial analysis uses publicly available data. Once you claim your building and connect your utility accounts, your specific usage data and custom reports are completely private and secure."
    },
    {
      question: "What if my building isn't in the Chicago benchmarking database?",
      answer: "We now cover over 100,000 commercial buildings in Chicago. If your building isn't in the city's benchmarking database, we use building footprint data and apply industry-standard energy models from the EIA and NREL to estimate your usage and savings potential."
    },
    {
      question: "Can I use one report for a refinance or investor presentation?",
      answer: "Yes. The premium report is designed to be an investment-grade document. It includes clear ROI calculations, payback periods, and verified cost ranges suitable for lenders and investors."
    },
    {
      question: "How does the shared savings model work?",
      answer: "For qualifying portfolios, we cover the upfront cost of the analysis and software. In exchange, we take a percentage of the verified utility savings generated by the improvements over a 24-36 month period."
    }
  ];

  return (
    <div className="bg-bg text-primary min-h-screen">
      {/* Hero Section */}
      <section className="relative pt-32 pb-24 px-4 sm:px-6 lg:px-8 max-w-7xl mx-auto text-center">
        <h1 className="text-5xl md:text-7xl font-semibold tracking-tight mb-8 max-w-4xl mx-auto leading-tight text-primary">
          Simple pricing. Savings-first model.
        </h1>
        <p className="text-xl text-primary/60 mb-12 max-w-2xl mx-auto leading-relaxed">
          Start for free. Only pay when you're ready to act — or let your savings pay for everything.
        </p>
      </section>

      {/* Pricing Tier Cards Section */}
      <section className="pb-24 px-4 sm:px-6 lg:px-8 max-w-7xl mx-auto">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 items-center">
          {/* Free Tier */}
          <div className="bg-bg rounded-[2rem] p-8 border border-black/5 h-full flex flex-col shadow-sm">
            <h3 className="text-2xl font-semibold text-primary mb-2 tracking-tight">Discover</h3>
            <div className="flex items-baseline gap-1 mb-6">
              <span className="text-5xl font-semibold text-primary tracking-tight">$0</span>
              <span className="text-primary/60">/forever</span>
            </div>
            <div className="h-px w-full bg-black/5 mb-8"></div>
            <ul className="space-y-4 mb-8 flex-grow">
              <li className="flex items-start gap-3 text-primary/70">
                <CheckCircle2 className="w-5 h-5 text-primary shrink-0 mt-0.5" />
                <span>Building loss estimate</span>
              </li>
              <li className="flex items-start gap-3 text-primary/70">
                <CheckCircle2 className="w-5 h-5 text-primary shrink-0 mt-0.5" />
                <span>Annual energy cost breakdown</span>
              </li>
              <li className="flex items-start gap-3 text-primary/70">
                <CheckCircle2 className="w-5 h-5 text-primary shrink-0 mt-0.5" />
                <span>ENERGY STAR score and peer rank</span>
              </li>
              <li className="flex items-start gap-3 text-primary/70">
                <CheckCircle2 className="w-5 h-5 text-primary shrink-0 mt-0.5" />
                <span>Top inefficiency categories identified</span>
              </li>
              <li className="flex items-start gap-3 text-primary/70">
                <CheckCircle2 className="w-5 h-5 text-primary shrink-0 mt-0.5" />
                <span>One improvement recommendation preview</span>
              </li>
            </ul>
            <Link 
              to="/platform"
              className="w-full bg-white border border-black/10 hover:bg-black/5 text-primary px-6 py-4 rounded-full font-medium text-lg transition-colors shadow-sm text-center"
            >
              Start Free
            </Link>
          </div>

          {/* Report Tier */}
          <div className="bg-white rounded-[2rem] p-8 border-2 border-primary relative shadow-md h-full flex flex-col transform md:-translate-y-4">
            <div className="absolute top-0 right-0 bg-primary text-white text-xs font-semibold px-4 py-1.5 rounded-bl-2xl rounded-tr-[1.8rem] uppercase tracking-wider">
              Most Popular
            </div>
            <h3 className="text-2xl font-semibold text-primary mb-2 tracking-tight">Analyze</h3>
            <div className="flex items-baseline gap-1 mb-6">
              <span className="text-5xl font-semibold text-primary tracking-tight">$149</span>
              <span className="text-primary/60">/building</span>
            </div>
            <div className="h-px w-full bg-primary/20 mb-8"></div>
            <ul className="space-y-4 mb-8 flex-grow">
              <li className="flex items-start gap-3 text-primary/70">
                <CheckCircle2 className="w-5 h-5 text-primary shrink-0 mt-0.5" />
                <span>Everything in Discover</span>
              </li>
              <li className="flex items-start gap-3 text-primary/70">
                <CheckCircle2 className="w-5 h-5 text-primary shrink-0 mt-0.5" />
                <span className="font-semibold text-primary">Full premium report PDF</span>
              </li>
              <li className="flex items-start gap-3 text-primary/70">
                <CheckCircle2 className="w-5 h-5 text-primary shrink-0 mt-0.5" />
                <span>All three prioritized recommendations with full ROI detail</span>
              </li>
              <li className="flex items-start gap-3 text-primary/70">
                <CheckCircle2 className="w-5 h-5 text-primary shrink-0 mt-0.5" />
                <span>Complete rebate and incentive eligibility list</span>
              </li>
              <li className="flex items-start gap-3 text-primary/70">
                <CheckCircle2 className="w-5 h-5 text-primary shrink-0 mt-0.5" />
                <span>Five and ten year savings projections</span>
              </li>
              <li className="flex items-start gap-3 text-primary/70">
                <CheckCircle2 className="w-5 h-5 text-primary shrink-0 mt-0.5" />
                <span>Implementation cost ranges for Chicago market</span>
              </li>
              <li className="flex items-start gap-3 text-primary/70">
                <CheckCircle2 className="w-5 h-5 text-primary shrink-0 mt-0.5" />
                <span>Downloadable and shareable report link</span>
              </li>
            </ul>
            <Link 
              to="/payment"
              className="w-full bg-accent hover:bg-accent-dark text-white px-6 py-4 rounded-full font-medium text-lg transition-colors shadow-sm text-center"
            >
              Get Full Report
            </Link>
          </div>

          {/* Portfolio Tier */}
          <div className="bg-bg rounded-[2rem] p-8 border border-black/5 h-full flex flex-col shadow-sm">
            <h3 className="text-2xl font-semibold text-primary mb-2 tracking-tight">Optimize</h3>
            <div className="flex items-baseline gap-1 mb-6 min-h-[4rem]">
              <span className="text-3xl font-semibold text-primary tracking-tight">Enterprise</span>
            </div>
            <div className="h-px w-full bg-black/5 mb-8"></div>
            <ul className="space-y-4 mb-8 flex-grow">
              <li className="flex items-start gap-3 text-primary/70">
                <CheckCircle2 className="w-5 h-5 text-primary shrink-0 mt-0.5" />
                <span>Everything in Analyze for unlimited buildings</span>
              </li>
              <li className="flex items-start gap-3 text-primary/70">
                <CheckCircle2 className="w-5 h-5 text-primary shrink-0 mt-0.5" />
                <span>Portfolio dashboard with aggregate savings view</span>
              </li>
              <li className="flex items-start gap-3 text-primary/70">
                <CheckCircle2 className="w-5 h-5 text-primary shrink-0 mt-0.5" />
                <span>Monthly utility tracking and predicted vs actual dashboard</span>
              </li>
              <li className="flex items-start gap-3 text-primary/70">
                <CheckCircle2 className="w-5 h-5 text-primary shrink-0 mt-0.5" />
                <span>Automatic alerts for new rebate programs</span>
              </li>
              <li className="flex items-start gap-3 text-primary/70">
                <CheckCircle2 className="w-5 h-5 text-primary shrink-0 mt-0.5" />
                <span>Dedicated account support</span>
              </li>
              <li className="flex items-start gap-3 text-primary/70">
                <CheckCircle2 className="w-5 h-5 text-primary shrink-0 mt-0.5" />
                <span>API access for property management integrations</span>
              </li>
              <li className="flex items-start gap-3 text-primary/70">
                <CheckCircle2 className="w-5 h-5 text-primary shrink-0 mt-0.5" />
                <span>White-label option available</span>
              </li>
            </ul>
            <Link 
              to="/contact"
              className="w-full bg-white border border-black/10 hover:bg-black/5 text-primary px-6 py-4 rounded-full font-medium text-lg transition-colors shadow-sm text-center"
            >
              Talk to Sales
            </Link>
          </div>
        </div>
      </section>


      {/* FAQ Section */}
      <section className="py-24 bg-white border-y border-black/5">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <h2 className="text-3xl font-semibold text-primary mb-12 text-center tracking-tight">Common questions.</h2>
          <div className="space-y-4">
            {faqs.map((faq, idx) => (
              <div key={idx} className="bg-bg border border-black/5 rounded-2xl overflow-hidden shadow-sm">
                <button 
                  onClick={() => setOpenFaq(openFaq === idx ? null : idx)}
                  className="w-full px-6 py-5 flex items-center justify-between text-left focus:outline-none"
                >
                  <span className="font-semibold text-primary">{faq.question}</span>
                  <ChevronDown className={`w-5 h-5 text-primary/40 transition-transform ${openFaq === idx ? 'rotate-180' : ''}`} />
                </button>
                {openFaq === idx && (
                  <div className="px-6 pb-5 text-primary/70 leading-relaxed">
                    {faq.answer}
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Bottom CTA */}
      <section className="py-24 bg-bg text-center">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <h2 className="text-4xl md:text-5xl font-semibold text-primary mb-6 tracking-tight">See your number first. Decide later.</h2>
          <p className="text-xl text-primary/60 mb-10">No credit card. No account. Just your building address.</p>
          <Link 
            to="/"
            className="inline-flex items-center justify-center gap-2 bg-accent hover:bg-accent-dark text-white px-10 py-5 rounded-full font-medium text-xl transition-colors shadow-sm"
          >
            Analyze Your Building
            <ArrowRight className="w-6 h-6" />
          </Link>
        </div>
      </section>
    </div>
  );
}
