import { ArrowRight, CheckCircle2, ChevronDown, Sparkles, FileText, Wrench, Building2, Percent, Zap } from 'lucide-react';
import { useState } from 'react';
import { Link } from 'react-router-dom';

export function PricingPage() {
  const [openFaq, setOpenFaq] = useState<number | null>(0);

  const faqs = [
    {
      question: "How are the financial estimates calculated?",
      answer: "We use your building's reported energy usage from the Chicago Benchmarking Ordinance and apply current ComEd and Peoples Gas commercial rates. We then compare your performance to similar buildings in Chicago to identify the gap between your current spend and optimal efficiency."
    },
    {
      question: "What data does Civic Energy use?",
      answer: "We aggregate data from the City of Chicago Benchmarking Ordinance, ComEd and Peoples Gas rate schedules, NOAA Chicago weather station, Cook County Assessor property records, and ENERGY STAR Portfolio Manager."
    },
    {
      question: "Is my building's data private?",
      answer: "The initial analysis uses publicly available data. Once you claim your building and connect your utility accounts, your specific usage data and custom reports are completely private and secure."
    },
    {
      question: "What if my building isn't in the Chicago benchmarking database?",
      answer: "We now cover over 100,000 commercial buildings in Chicago. If your building isn't in the city's benchmarking database, we use building footprint data and apply industry-standard energy models from the EIA and NREL to estimate your usage and savings potential."
    },
    {
      question: "How does the shared savings model work?",
      answer: "For qualifying portfolios, we cover the upfront cost of the analysis and software. In exchange, we take a percentage of the verified utility savings generated by the improvements over a 24-36 month period."
    }
  ];

  return (
    <div className="bg-bg text-primary min-h-screen">
      {/* Hero Section */}
      <section className="relative pt-32 pb-24 px-4 sm:px-6 lg:px-8 max-w-7xl mx-auto text-center">
        <h1 className="text-5xl md:text-7xl font-semibold tracking-tight mb-8 max-w-4xl mx-auto leading-tight text-primary">
          Simple pricing. Savings-first model.
        </h1>
        <p className="text-xl text-primary/60 mb-12 max-w-2xl mx-auto leading-relaxed">
          No upfront cost. No risk. You only pay us after you start saving money.
        </p>
      </section>

      {/* Pricing Models Section */}
      <section className="pb-24 px-4 sm:px-6 lg:px-8 max-w-7xl mx-auto">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          
          {/* Main Model - Pay Only When You Save */}
          <div className="bg-white rounded-[2rem] p-10 border-2 border-primary relative shadow-md flex flex-col md:col-span-2 lg:col-span-1">
            <div className="absolute top-0 right-0 bg-primary text-white text-xs font-semibold px-4 py-1.5 rounded-bl-2xl rounded-tr-[1.8rem] uppercase tracking-wider">
              Our Main Model
            </div>
            <div className="flex items-center gap-3 mb-4">
              <div className="w-12 h-12 rounded-2xl bg-emerald-500/10 flex items-center justify-center shrink-0">
                <Percent className="w-6 h-6 text-emerald-600" />
              </div>
              <h3 className="text-3xl font-semibold text-primary tracking-tight">Pay Only When You Save</h3>
            </div>
            <p className="text-xl text-primary/70 mb-6 font-medium">No upfront cost. No risk.</p>
            <p className="text-primary/70 mb-8 leading-relaxed">
              We find where your building is wasting energy (electricity, heating, cooling), and show you how to fix it. You only pay us after you start saving money.
            </p>
            
            <div className="bg-bg rounded-2xl p-6 mb-8 border border-black/5">
              <h4 className="font-semibold text-primary mb-4">Example:</h4>
              <ul className="space-y-3">
                <li className="flex justify-between items-center text-primary/80">
                  <span>You save</span>
                  <span className="font-semibold text-primary">$100,000/year</span>
                </li>
                <li className="flex justify-between items-center text-primary/80">
                  <span>We take</span>
                  <span className="font-semibold text-emerald-600">20–30% of the savings</span>
                </li>
                <li className="flex justify-between items-center text-primary/80 pt-3 border-t border-black/10">
                  <span>You keep the rest</span>
                  <span className="font-semibold text-primary text-lg">$70k–$80k/year</span>
                </li>
              </ul>
            </div>

            <ul className="space-y-4 mb-8 flex-grow">
              <li className="flex items-start gap-3 text-primary/80">
                <CheckCircle2 className="w-6 h-6 text-emerald-500 shrink-0" />
                <span className="font-medium">No savings → you pay nothing</span>
              </li>
              <li className="flex items-start gap-3 text-primary/80">
                <CheckCircle2 className="w-6 h-6 text-emerald-500 shrink-0" />
                <span className="font-medium">We succeed only when you do</span>
              </li>
            </ul>
            <Link 
              to="/platform"
              className="w-full bg-accent hover:bg-accent-dark text-white px-6 py-4 rounded-full font-medium text-lg transition-colors shadow-sm text-center"
            >
              Get Started for Free
            </Link>
          </div>

          {/* Quick Energy Reports */}
          <div className="bg-bg rounded-[2rem] p-10 border border-black/5 flex flex-col shadow-sm">
            <div className="flex items-center gap-3 mb-4">
              <div className="w-12 h-12 rounded-2xl bg-blue-500/10 flex items-center justify-center shrink-0">
                <FileText className="w-6 h-6 text-blue-600" />
              </div>
              <h3 className="text-3xl font-semibold text-primary tracking-tight">Quick Energy Reports (One-Time)</h3>
            </div>
            <p className="text-xl text-primary/70 mb-4 font-medium">Want insights without commitment? Start here.</p>
            <p className="text-primary/70 mb-4">Get a simple report showing:</p>
            <ul className="list-disc list-inside text-primary/70 mb-8 space-y-1">
              <li>Where you’re wasting energy</li>
              <li>How much you could save</li>
              <li>What to fix first</li>
            </ul>

            <h4 className="font-semibold text-primary mb-4">Pricing:</h4>
            <div className="grid grid-cols-2 gap-4 mb-8">
              <div className="bg-white rounded-2xl p-6 border border-black/5 text-center">
                <div className="text-3xl font-semibold text-primary mb-1">$199</div>
                <div className="text-sm font-medium text-primary/60">One building</div>
              </div>
              <div className="bg-white rounded-2xl p-6 border border-black/5 text-center">
                <div className="text-3xl font-semibold text-primary mb-1">$499</div>
                <div className="text-sm font-medium text-primary/60">Multiple buildings</div>
              </div>
            </div>
            
            <ul className="space-y-4 mb-8 flex-grow">
              <li className="flex items-start gap-3 text-primary/70">
                <CheckCircle2 className="w-5 h-5 text-primary shrink-0 mt-0.5" />
                <span>Fast</span>
              </li>
              <li className="flex items-start gap-3 text-primary/70">
                <CheckCircle2 className="w-5 h-5 text-primary shrink-0 mt-0.5" />
                <span>Easy to understand</span>
              </li>
              <li className="flex items-start gap-3 text-primary/70">
                <CheckCircle2 className="w-5 h-5 text-primary shrink-0 mt-0.5" />
                <span>No long-term contract</span>
              </li>
            </ul>
            <Link 
              to="/payment"
              className="w-full bg-white border border-black/10 hover:bg-black/5 text-primary px-6 py-4 rounded-full font-medium text-lg transition-colors shadow-sm text-center mt-auto"
            >
              Get a Report
            </Link>
          </div>

          {/* Need Vendors? */}
          <div className="bg-bg rounded-[2rem] p-10 border border-black/5 flex flex-col shadow-sm">
            <div className="flex items-center gap-3 mb-4">
              <div className="w-12 h-12 rounded-2xl bg-amber-500/10 flex items-center justify-center shrink-0">
                <Wrench className="w-6 h-6 text-amber-600" />
              </div>
              <h3 className="text-2xl font-semibold text-primary tracking-tight">Need Vendors? We Connect You</h3>
            </div>
            <p className="text-primary/70 mb-8 leading-relaxed">
              Skip the search. Get the right contractors. If your building needs upgrades (HVAC, lighting, etc.), we connect you with trusted contractors.
            </p>
            
            <ul className="space-y-4 mb-8 flex-grow">
              <li className="flex items-start gap-3 text-primary/70">
                <CheckCircle2 className="w-5 h-5 text-amber-500 shrink-0 mt-0.5" />
                <span>No random calls</span>
              </li>
              <li className="flex items-start gap-3 text-primary/70">
                <CheckCircle2 className="w-5 h-5 text-amber-500 shrink-0 mt-0.5" />
                <span>Only relevant, high-quality matches</span>
              </li>
              <li className="flex items-start gap-3 text-primary/70">
                <CheckCircle2 className="w-5 h-5 text-amber-500 shrink-0 mt-0.5" />
                <span>Saves you time and effort</span>
              </li>
            </ul>
          </div>

          {/* Large Teams */}
          <div className="bg-bg rounded-[2rem] p-10 border border-black/5 flex flex-col shadow-sm relative overflow-hidden">
            <div className="absolute -right-8 -bottom-8 opacity-[0.03] pointer-events-none">
              <Building2 className="w-64 h-64" />
            </div>
            <div className="relative z-10">
              <div className="flex items-center gap-3 mb-4">
                <div className="w-12 h-12 rounded-2xl bg-purple-500/10 flex items-center justify-center shrink-0">
                  <Building2 className="w-6 h-6 text-purple-600" />
                </div>
                <h3 className="text-2xl font-semibold text-primary tracking-tight">For Large Teams & Partners</h3>
              </div>
              <p className="text-primary/70 mb-4 leading-relaxed font-medium">
                Manage multiple buildings or need deeper insights?
              </p>
              <p className="text-primary/70 mb-2">We offer tools for:</p>
              <ul className="list-disc list-inside text-primary/70 mb-6 space-y-1">
                <li>Property managers</li>
                <li>Real estate portfolios</li>
                <li>Energy consultants</li>
              </ul>
              
              <p className="text-primary/70 mb-4 font-semibold">Includes:</p>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-x-4 gap-y-2 mb-8">
                <div className="flex items-center gap-2 text-sm text-primary/70 bg-white px-3 py-2 rounded-lg border border-black/5">
                  <Zap className="w-4 h-4 text-purple-500" /> Advanced dashboards
                </div>
                <div className="flex items-center gap-2 text-sm text-primary/70 bg-white px-3 py-2 rounded-lg border border-black/5">
                  <Zap className="w-4 h-4 text-purple-500" /> Portfolio tracking
                </div>
                <div className="flex items-center gap-2 text-sm text-primary/70 bg-white px-3 py-2 rounded-lg border border-black/5">
                  <Zap className="w-4 h-4 text-purple-500" /> API access
                </div>
              </div>

              <div className="bg-primary text-white rounded-2xl p-6 mt-auto">
                <div className="text-sm text-white/60 uppercase font-bold tracking-wider mb-1">Custom pricing</div>
                <div className="text-3xl font-semibold">starts at $24K/year</div>
              </div>
            </div>
          </div>

        </div>
      </section>

      {/* FAQ Section */}
      <section className="py-24 bg-white border-y border-black/5">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <h2 className="text-3xl font-semibold text-primary mb-12 text-center tracking-tight">Common questions.</h2>
          <div className="space-y-4">
            {faqs.map((faq, idx) => (
              <div key={idx} className="bg-bg border border-black/5 rounded-2xl overflow-hidden shadow-sm">
                <button 
                  onClick={() => setOpenFaq(openFaq === idx ? null : idx)}
                  className="w-full px-6 py-5 flex items-center justify-between text-left focus:outline-none"
                >
                  <span className="font-semibold text-primary">{faq.question}</span>
                  <ChevronDown className={`w-5 h-5 text-primary/40 transition-transform ${openFaq === idx ? 'rotate-180' : ''}`} />
                </button>
                {openFaq === idx && (
                  <div className="px-6 pb-5 text-primary/70 leading-relaxed">
                    {faq.answer}
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Bottom CTA */}
      <section className="py-24 bg-bg text-center">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <h2 className="text-4xl md:text-5xl font-semibold text-primary mb-6 tracking-tight">See your number first. Decide later.</h2>
          <p className="text-xl text-primary/60 mb-10">No credit card. No account. Just your building address.</p>
          <Link 
            to="/"
            className="inline-flex items-center justify-center gap-2 bg-accent hover:bg-accent-dark text-white px-10 py-5 rounded-full font-medium text-xl transition-colors shadow-sm"
          >
            Analyze Your Building
            <ArrowRight className="w-6 h-6" />
          </Link>
        </div>
      </section>
    </div>
  );
}
